version: "2"
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - dupl
    - errcheck
    - errname
    - exhaustruct
    - forbidigo
    - funlen
    - gochecknoglobals
    - gocognit
    - gocritic
    - govet
    - intrange
    - ireturn
    - mnd
    - musttag
    - nestif
    - nilnil
    - nlreturn
    - paralleltest
    - tagliatelle
    - testableexamples
    - testpackage
    - thelper
    - varnamelen
    - wrapcheck
    - wsl
    - wsl_v5
    - staticcheck
    - recvcheck
    - noinlineerr
    - funcorder
  settings:
    errcheck:
      check-type-assertions: true
    funlen:
      lines: 100
      statements: 50
    gocognit:
      min-complexity: 10
    godot:
      period: false
    gosec:
      excludes:
        - G115
    govet:
      enable-all: true
      settings:
        shadow:
          strict: true
    lll:
      line-length: 100
      tab-width: 2
    nakedret:
      max-func-lines: 0
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 50
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - prefix(github.com/leafzone)
        - default
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
